### ISSUE TITLE
User guide needed

### ISSUE THREAD

**Issue by oanaaa13** [andru47/smkhe#11]
Hi, I find your project very interesting and I'd like to use the library for a personal project(university) which includes a private voting system on blockchain. 

Could you send me a guide or a brief description of how could I include the library in my project? 

I am fairly new to C++ and I don't know how to use libraries from Github. I mostly use python with pip that does the job for me. 
Also, I'd like to mention that I mostly use Windows as OS, but if it's a must to get on Linux, then that's ok.
Thanks!

**Comment by andru47** [comment]
@oanaaa13 Hi! I would say that you better use bigger frameworks for this, such as [SEAL](https://github.com/microsoft/SEAL). They have a big user guide and their framework is better tested. To install my library you need to clone it and include it in your CMake project. You can search on Google how to create a CMake project and how to add dependencies in it.

**Comment by oanaaa13** [comment]
I think your library has the multi-key homomorphic encryption, while SEAL doesn't, that's why I want to use it. 
Do you think I could use SEAL for multi key?

**Comment by oanaaa13** [comment]
Or could you suggest some big library with can handle multikey HE?

**Comment by andru47** [comment]
@oanaaa13 SEAL doesn't provide multi-key functionality. Another library that I was using is [Lattigo](https://github.com/tuneinsight/lattigo/pull/130), they have the multi-key in development (see the attached PR), it's written in Go and you can interoperate with C++.

**Comment by oanaaa13** [comment]
Thanks, I will try to use Lattigo, hopefully I can make it work :D
