### ISSUE TITLE
Hello, what platform can smkhe run on? Windows or Linux?

### ISSUE THREAD

**Issue by sunshine-lh** [andru47/smkhe#9]

**Comment by andru47** [comment]
Hi @sunshine-lh! As long as you have the [protobuf](https://github.com/protocolbuffers/protobuf) library installed, it should work on both Windows and Linux.

**Comment by sunshine-lh** [comment]
> Hi @sunshine-lh! As long as you have the [protobuf](https://github.com/protocolbuffers/protobuf) library installed, it should work on both Windows and Linux.

Hello @andru47! Do you have any requirements for the version of protobuf library？

**Comment by andru47** [comment]
@sunshine-lh There shouldn't be any specific protobuf version. I remember using [v3.19.4](https://github.com/protocolbuffers/protobuf/releases/tag/v3.19.4) while I was testing it.
